# left dock: big touch targets
global-settings { watch-config-file = true; }
bar {
	output = all;
	position = left;
	alignment = center;
	size = 76;
	icon-padding = 10;
	background-colour = "#1b2330e6";
	border = 0;
	radius = 0;
	button { image-path = "/usr/share/icons/Papirus/64x64/apps/applications-all.svg";          command[mouse-left] = "fuzzel"; command[touch] = "fuzzel"; }
	button { image-path = "/usr/share/icons/Papirus/64x64/apps/utilities-terminal.svg";        command[mouse-left] = "foot"; command[touch] = "foot"; }
	button { image-path = "/usr/share/icons/Papirus/64x64/apps/web-browser.svg";               command[mouse-left] = "netsurf"; command[touch] = "netsurf"; }
	button { image-path = "/usr/share/icons/Papirus/64x64/apps/accessories-text-editor.svg";   command[mouse-left] = "mousepad"; command[touch] = "mousepad"; }
	button { image-path = "/usr/share/icons/Papirus/64x64/apps/system-file-manager.svg";       command[mouse-left] = "pcmanfm"; command[touch] = "pcmanfm"; }
	button { image-path = "/usr/share/icons/Papirus/64x64/devices/input-keyboard.svg";         command[mouse-left] = "/usr/local/bin/casper-kbd"; command[touch] = "/usr/local/bin/casper-kbd"; }
}
